### ISSUE TITLE
Site does not function in Firefox

### ISSUE THREAD

**Issue by waldoj** [stamen/usopendata#38]
No projects load. The site is blank except for the header. The error is:

```
TypeError: projectList.map is not a function
```

**Comment by divergentdave** [comment]
I'm getting this error too. `projectList.map` shows up in a `render` function for some component. The first couple times, render gets called with projectList set to the empty list, and the third time, it gets called with storeState.projectList.data set to a Response object, not a list. Looking at the same thing in Chrome, storeState.projectList.data is set to a list of five objects.

**Comment by divergentdave** [comment]
I traced the difference down to https://github.com/stamen/usopendata/blob/9be05b920690f6c23f518bc578f7a043a470ba95/js/models/transport.js#L49. In both debuggers, `returnVal` appears to be a Promise, however Chrome takes the `returnVal instanceof Promise` branch and Firefox takes the else branch. As a result, the Promise for a Response in Firefox is treated as if it were already parsed and cached, so the JSON parser never gets run on it. This leads to the other issues down the line, eventually resulting in calling an array method on a Response.

Not sure what the root cause of this is, but my first guess would be dueling Promise classes from the browser and from libraries.

**Comment by waldoj** [comment]
Wow, I'm glad you chased that down, because I was _not_ gonna figure that out. This is a great basis for me to start identifying the root case. Thank you!

**Comment by waldoj** [comment]
@ericsoko kindly fixed this with dfd4dbcde68a22cba60d6f9f2fd11dd7f42bc520.
